<a href="https://colab.research.google.com/github/Sohailsadeed/ml-libraries/blob/main/pandas/pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
series=pd.Series([10,20,30,'wizard'])
series

0        10
1        20
2        30
3    wizard
dtype: object

In [ ]:
series.values

array([10, 20, 30, 'wizard'], dtype=object)

In [ ]:
series.dtype

dtype('O')

In [ ]:
series.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(series.name)

None

In [ ]:
series.name="Junk INTEGERS";

In [ ]:
print(series.name)

Junk INTEGERS

In [ ]:
series

0        10
1        20
2        30
3    wizard
Name: Junk INTEGERS, dtype: object

In [ ]:
series.iloc[1:3]

1    20
2    30
Name: Junk INTEGERS, dtype: object

In [ ]:
series.iloc[3]=15

In [ ]:
series

0    10
1    20
2    30
3    15
Name: Junk INTEGERS, dtype: object

In [ ]:
series.name='score'

In [ ]:
index=['john','alex','spparke','insane']
series.index=index
series

john       10
alex       20
spparke    30
insane     15
Name: score, dtype: object

In [ ]:
print("Score of spparke is:",series['spparke'])

Score of spparke is: 30

In [ ]:
series.loc['insane']

15

In [ ]:
series.loc[['john','alex']]

john    10
alex    20
Name: score, dtype: object

In [ ]:
series['john':'spparke']

john       10
alex       20
spparke    30
Name: score, dtype: object

In [ ]:
human_scores={
    "Allen": 10,
    "Alex":30,
    "Jake":50,
    "Sam":25,
    "Emily":60
}
human_scores

{'Allen': 10, 'Alex': 30, 'Jake': 50, 'Sam': 25, 'Emily': 60}

In [ ]:
scores = pd.Series(human_scores,name="Score sheet")
scores

Allen    10
Alex     30
Jake     50
Sam      25
Emily    60
Name: Score sheet, dtype: int64

In [ ]:
scores[scores>20]

Alex     30
Jake     50
Sam      25
Emily    60
Name: Score sheet, dtype: int64

In [ ]:
[scores>20]

[Allen    False
 Alex      True
 Jake      True
 Sam       True
 Emily     True
 Name: Score sheet, dtype: bool]

In [ ]:
import numpy as np
ser = pd.Series(['a',1,np.nan,2,np.nan])
ser.isnull().sum()

np.int64(2)

In [ ]:
# DataFrame:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [ ]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [ ]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
# loc and iloc
df.iloc[0:3, 0:4:2] #rows, columns

      Name Department
0    Alice         HR
1      Bob         IT
2  Charlie    Finance

In [ ]:
df.loc[1:4,['Name','Salary']]

      Name   Salary
1      Bob  60000.0
2  Charlie  70000.0
3    David  62000.0
4      Eve      NaN

In [ ]:
df['Age']

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df[['Age','Salary']]

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  35.0  70000.0
3   NaN  62000.0
4  29.0      NaN
5  25.0  50000.0

In [ ]:
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [ ]:
# Broadcasting
df['Salary'] = df["Salary"] + 5000
df['Salary']

0    65000.0
1    75000.0
2    85000.0
3    77000.0
4        NaN
5    65000.0
Name: Salary, dtype: float64

In [ ]:
# Renaming columns
df.rename(columns={'Salary':'Pay'},inplace=True)
df

      Name   Age Department      Pay
0    Alice  25.0         HR  65000.0
1      Bob  30.0         IT  75000.0
2  Charlie  35.0    Finance  85000.0
3    David   NaN         IT  77000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  65000.0

In [ ]:
df ['Department'].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
df["Department"].value_counts()

Department
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
# Adding new columns
df["Promoted Salary"] = df["Pay"] + df["Pay"] * 10 / 100
df

      Name   Age Department      Pay  Promoted Salary
0    Alice  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
3    David   NaN         IT  77000.0          84700.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  65000.0          71500.0

In [ ]:
# Data Cleaning
df.dropna(how = "any") #Drop any row that has any null value

      Name   Age Department      Pay  Promoted Salary
0    Alice  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
5    Alice  25.0         HR  65000.0          71500.0

In [ ]:
df.dropna(how="all") #Drop only if all the values in a row are null

      Name   Age Department      Pay  Promoted Salary
0    Alice  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
3    David   NaN         IT  77000.0          84700.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  65000.0          71500.0

In [ ]:
#Dealing with missing values by filling them up
df["Age"].fillna(df['Age'].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Pay"].fillna(df['Pay'].median())

0    65000.0
1    75000.0
2    85000.0
3    77000.0
4    75000.0
5    65000.0
Name: Pay, dtype: float64

In [ ]:
# Using forward and backward fill
df["Age"].fillna(method="ffill")

/tmp/ipython-input-310954073.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df['Age'].fillna(method='bfill')

/tmp/ipython-input-3224957626.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method='bfill')

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df

      Name   Age Department      Pay  Promoted Salary
0    Alice  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
3    David   NaN         IT  77000.0          84700.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  65000.0          71500.0

In [ ]:
#Replacing values
df["Name"].replace("Alice","Spparke")

0    Spparke
1        Bob
2    Charlie
3      David
4        Eve
5    Spparke
Name: Name, dtype: object

In [ ]:
df["Name"] = df["Name"].replace("Alice","Spparke") # Makes changes to original dataset
df

      Name   Age Department      Pay  Promoted Salary
0  Spparke  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
3    David   NaN         IT  77000.0          84700.0
4      Eve  29.0         HR      NaN              NaN
5  Spparke  25.0         HR  65000.0          71500.0

In [ ]:
# Duplicates
df_duplicate = df[df.duplicated(keep = "last")] #Default parameter is keep="first"
df_duplicate

      Name   Age Department      Pay  Promoted Salary
0  Spparke  25.0         HR  65000.0          71500.0

In [ ]:
df = df.drop_duplicates()
df

      Name   Age Department      Pay  Promoted Salary
0  Spparke  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          82500.0
2  Charlie  35.0    Finance  85000.0          93500.0
3    David   NaN         IT  77000.0          84700.0
4      Eve  29.0         HR      NaN              NaN

In [ ]:
# Invalid values
# Lambda -> python
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x-5000 if x>82000 else x)
df

      Name   Age Department      Pay  Promoted Salary
0  Spparke  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          77500.0
2  Charlie  35.0    Finance  85000.0          83500.0
3    David   NaN         IT  77000.0          79700.0
4      Eve  29.0         HR      NaN              NaN

In [ ]:
name="alex_spies"
df[["first_name", "last_name"]] = df["name"].str.split("_") #Will work if there is a column named 'name', and contains value in the form
                                                            # 'xxx_yyy' which will further produce xxx as 'first_name' and yyy as 'last_name'

KeyError: 'name'

In [ ]:
#Apply and lambda
df["Age"] = df["Age"].apply(lambda x: x*2)
df

      Name   Age Department      Pay  Promoted Salary
0  Spparke  50.0         HR  65000.0          71500.0
1      Bob  60.0         IT  75000.0          77500.0
2  Charlie  70.0    Finance  85000.0          83500.0
3    David   NaN         IT  77000.0          79700.0
4      Eve  58.0         HR      NaN              NaN

In [ ]:
def original_age(x):
  return x/2
df["Age"] = df["Age"].apply(original_age)
df

      Name   Age Department      Pay  Promoted Salary
0  Spparke  25.0         HR  65000.0          71500.0
1      Bob  30.0         IT  75000.0          77500.0
2  Charlie  35.0    Finance  85000.0          83500.0
3    David   NaN         IT  77000.0          79700.0
4      Eve  29.0         HR      NaN              NaN

In [ ]:
# Joins and Merges

department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [ ]:
pd.concat([df,df2])

,Name,Age,Department,Pay,Promoted Salary,Dept,Location,Manager
0,Spparke,25.0,HR,65000.0,71500.0,NaN,NaN,NaN
1,Bob,30.0,IT,75000.0,77500.0,NaN,NaN,NaN
2,Charlie,35.0,Finance,85000.0,83500.0,NaN,NaN,NaN
3,David,NaN,IT,77000.0,79700.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [ ]:
pd.concat([df,df2],axis=1)

,Name,Age,Department,Pay,Promoted Salary,Dept,Location,Manager
0,Spparke,25.0,HR,65000.0,71500.0,HR,New York,Laura
1,Bob,30.0,IT,75000.0,77500.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,85000.0,83500.0,Finance,Chicago,Nina
3,David,NaN,IT,77000.0,79700.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.merge(df, df2, left_on='Department', right_on='Dept')

,Name,Age,Department,Pay,Promoted Salary,Dept,Location,Manager
0,Spparke,25.0,HR,65000.0,71500.0,HR,New York,Laura
1,Bob,30.0,IT,75000.0,77500.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,85000.0,83500.0,Finance,Chicago,Nina
3,David,NaN,IT,77000.0,79700.0,IT,San Francisco,Steve
4,Eve,29.0,HR,NaN,NaN,HR,New York,Laura

In [ ]:
data = pd.read_csv("Boston-house-price-data.csv")

In [ ]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
data.shape

(506, 14)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [ ]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000